.TH BL 1 bibliotheca-latina
.SH NAME
bl \- bibliotheca-latina \- part-of-speech tagger for Latin text documents
.SH SYNOPSIS
.B bl
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
.B bl
identifies parts of speech using
.B words
(William Whitaker's Words) and tags each word with single letters.
.SH AUTHORS
Written by Nenad Stoisavljevic <nenad@nenadstoisavljevic.xyz>.
.SH LICENSE
GPLv3
